name: cs7643-flood
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - rasterio
  - numpy
  - matplotlib
  - jupyterlab
  - notebook
  - ipykernel
  - pip
  - pip:
      - albumentations
      - torch
      - torchvision
      - tqdm